PREFIX reg: <http://metadataregistry.org/uri/profile/regap/>
PREFIX rdakit: <http://metadataregistry.org/uri/profile/rdakit/>

# Need to look for some properties:
	# is adapted as opera work
	# is adapted and musical theater work
# Also need to look for:
	# has work part - this is for content notes values

SELECT ?pSubject

WHERE {
	
}
