PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> 
PREFIX bf: <http://id.loc.gov/ontologies/bibframe/> 
PREFIX dc: <http://purl.org/dc/elements/1.1/> 
PREFIX dct: <http://purl.org/dc/terms/> 
PREFIX dpla: <http://dp.la/about/map/> 
PREFIX edm: <http://www.europeana.eu/schemas/edm/> 
PREFIX foaf: <http://xmlns.com/foaf/0.1/> 
PREFIX uwlc: <https://doi.org/10.6069/uwlib.55.D.1#> 
PREFIX rel: <http://id.loc.gov/vocabulary/relators/> 
PREFIX skos: <http://www.w3.org/2004/02/skos/core#> 
PREFIX void: <http://rdfs.org/ns/void#> 
PREFIX ldproc: <https://doi.org/10.6069/uwlib.55.b.2#> 
PREFIX plat: <https://doi.org/10.6069/uwlib.55.d.2#> 
PREFIX owl: <http://www.w3.org/2002/07/owl#> 

CONSTRUCT

	{
		<https://doi.org/10.6069/uwlib.55.A.3.1#cdm0> ?sp ?so .
		?bnode ?bp ?bo .
	}
WHERE

	{
		<https://doi.org/10.6069/uwlib.55.A.3.1#cdm0> ?sp ?so ;
			?sr2bn ?bnode .
		?bnode ?bp ?bo .
	}
